Feat(feature): Set timeouts and grace values for days exceeding 30
andela/hc-millennium-falcon pull request #12
Opened 2018-04-30 10:17 UTC by kasigazibrian

- Edits `hc_extras.py` to add the MONTH and YEAR parameters to the `hc_duration` function
- Edits the `check.js` to modify the `noUislider` with an increased range. The slider can now move from 1 month to 1 year allowing monthly grace and timeout periods.
- Edits the test_hc_extras.py` to add tests for the month and year parameters added.
- Edits the `hc/front/forms.py` to change the maximum time value form `25920000` to `31104000`. This allows for monthly grace period and timeout

[Feature #156577922](https://www.pivotaltracker.com/story/show/156577922)

2018-04-30 11:18 UTC, Rwothoromo reviewed
It looks good so far.

2018-05-01 09:10 UTC, emugaya commented
@kasigazibrian Follow the PR and Commit message template. Also, add a print screen of the new page to the PR.

2018-05-01 09:12 UTC, emugaya requested changes
Respond to comments added.

2018-05-02 11:43 UTC, kasigazibrian commented
@emugaya I have implemented the changed requested

2018-05-02 18:35 UTC, SoniaRMK commented
@kasigazibrian don't forget to add the `ready` label once our TTL marks this PR as approved

2018-05-03 06:50 UTC, emugaya approved these changes

2018-05-03 06:50 UTC, merged

2018-05-11 13:40 UTC, kasigazibrian commented
Sonia thank you for the reminder. I have implemented it