#156577920 Create a dashboard for failed checks
andela/hc-millennium-falcon pull request #13
Opened 2018-04-30 11:28 UTC by SoniaRMK

### What does this PR do?
This PR creates a dashboard for all failed checks for a particular user.
#### Description of Task to be completed?
**Edited files are**:
`hc/templates/base.html` *line 80*: Where failed checks was added to the navigation menu, 
`hc/front/views.py` line *line 62*: Where a function called `my_failed_checks` which filters out failed checks and returns them as a list, 
`hc/front/urls.py ` *line 34* : Where a route was added.
**New files created**: 
`hc/front/tests/test_my_failed_checks.py` which handles tests for the function created, 
`hc/templates/front/my_failed_checks.html` which is the UI for the dashboard.
#### How should this be manually tested?
Run the application, after login, create some checks and have some of those fail. Then navigate to failed checks using the link provided in the navigation menu
#### Any background context you want to provide?
Previously, there was no UI where a user could view only the failed checks.
#### What are the relevant pivotal tracker stories?
[#156577920](https://www.pivotaltracker.com/story/show/156577920)

2018-05-01 09:04 UTC, emugaya commented on hc/settings.py
> +DATABASES['default'] = dj_database_url.config(default="postgres://postgres:1234567890@localhost:/hc")
Why are we hardcoding the database? these settings should be picked from an environment variable

2018-05-01 09:05 UTC, emugaya commented on templates/front/my_failed_checks.html
> +{% extends "base.html" %}
The contents of this file look exactly like the ones in checks. Think of re-using this the checks template to instead of duplication this code.

2018-05-01 09:06 UTC, emugaya commented
@SoniaRMK Follow the PR and Commit message template. No need to list files changed as GitHub already does that for us.

2018-05-01 09:12 UTC, emugaya requested changes
Respond to comments added. And make sure our test coverage doesn't drop.

2018-05-02 11:11 UTC, SoniaRMK commented
@emugaya , I have made all the requested changes. kindly review my PR again. Thank you

2018-05-02 14:01 UTC, emugaya approved these changes

2018-05-03 06:25 UTC, merged