#156577928 Add help center
andela/hc-millennium-falcon pull request #27
Opened 2018-05-17 20:05 UTC by louiCoder

**What does this PR do?**
Gives the user the ability to be able to navigate through video tutorials , documentation of the system and also a live chat feature. 

**Description of Task to be completed?**
Categorise Docs, video tutorials and Frequently asked questions into one menu item for ease of access and also add a live chat feature in the application  

How should this be manually tested?
run `./manage.py makemigrations help`
run `./manage.py migrate`
run `./manage.py runserver`

Login into the application with you email and password or with link sent to email you have provided. then from the menu, Select a desired option from the help menu item located on the navigation bar. Choices to choose from are either FAQ(Frequently Asked Questions) to be posted by authenticated users, Docs and video tutorials

Any background context you want to provide?
Previously Docs was one of the main menu item in the navigation bar  and there were no video tutorials and the live chat feature was not present in the application

What are the relevant pivotal tracker stories?
[156577928](https://www.pivotaltracker.com/story/show/156577928)

Snapshot:
![image](https://user-images.githubusercontent.com/32771081/40200935-4a04ad44-5a26-11e8-8a5b-34ad39482f13.png)

2018-05-18 06:41 UTC, emugaya commented
@louiCoder Change the order on the drop down to `Docs, Videos, FAQ` Then remove the numbering. and show print-screens for all the views on the PR.

2018-05-18 06:43 UTC, emugaya commented on hc/help/migrations/0003_auto_20180517_1237.py
> +            old_name='Faq',
Leave the table name as `faqs` for frequently asked questions.

2018-05-18 06:43 UTC, emugaya commented on hc/help/models.py
> +
Add a date modified.

2018-05-18 06:44 UTC, emugaya commented on hc/help/models.py
> +        return '%s, %s, %d'%(self.question, self.answer, self.id)
Add new line at the end of the file.

2018-05-18 06:47 UTC, emugaya requested changes
Address the issues raised. Secondly, Use the current header settings for the Questions. You FAQs look foreign on the page.

2018-05-18 06:47 UTC, emugaya commented on hc/help/views.py
> +    return render(request, "help/videos.html", {"page":"help"})
Add a new line at the end of the file.

2018-05-18 06:47 UTC, emugaya commented on templates/base.html
> +                <!-- <li {% if page == 'docs' %} class="active" {% endif %}>
Remove commented out code.

2018-05-18 06:47 UTC, emugaya commented on templates/help/faq.html
> +        <!-- {% if messages.tags %}
Remove commented out code.

2018-05-18 12:17 UTC, Rwothoromo commented on hc/help/models.py
> +class Faqs(models.Model):
Perhaps the class should be `Faq` to stay inline with other class names

2018-05-18 12:19 UTC, Rwothoromo commented on hc/help/views.py
> +    qns = Faqs.objects.all()
Perhaps we can use more descriptive variables like `questions` instead of `qns`
So we'd have
```
questions = Faq.objects.all()
ctx = {"questions":questions, "page":"help"}
```
So someone can understand better when reading through.

2018-05-18 12:23 UTC, emugaya commented on templates/help/videos.html
> +{% extends "base.html" %}
Don't hardcode input. What if other stakeholders want to change the videos. Will they have to come and update the `html` file?

2018-05-21 06:50 UTC, emugaya approved these changes

2018-05-21 06:50 UTC, merged